SystemOrganization addCategory: #'Clap-Core'!
SystemOrganization addCategory: 'Clap-Core-DocExample'!
SystemOrganization addCategory: 'Clap-Core-DocWriter'!
SystemOrganization addCategory: 'Clap-Core-Exceptions'!
SystemOrganization addCategory: 'Clap-Core-Matcher'!
SystemOrganization addCategory: 'Clap-Core-Matches'!
SystemOrganization addCategory: 'Clap-Core-Parameters'!
SystemOrganization addCategory: 'Clap-Core-Support'!
